Repository hoaibao2k4/CakewaiTown, pull requests merged in 2025-03, with the labels that each got.

#9 #1 - Recommit homepage
  client/src/app/ai/page.tsx
Labels: feature

#20 #3 - refactoring cart page
  client/src/app/cart/page.tsx
  client/src/components/Cart/CartItem/index.tsx
Labels: feature

#19 #2 - refactoring-profile-page
  client/package-lock.json
  client/package.json
  client/src/app/account/address/page.tsx
  client/src/app/account/change-password/page.tsx
  client/src/app/account/layout.tsx
  client/src/app/account/orders/page.tsx
  client/src/app/account/page.tsx
  client/src/app/account/profile/page.tsx
  client/src/app/account/sidebar.tsx
  client/src/app/account/sidebarContent.tsx
  client/src/components/Breadcrumb/index.jsx
  client/src/components/Breadcrumb/index.tsx
Labels: feature

#26 fix bug in profile page - #2
  client/src/app/account/address/index.tsx
  client/src/app/account/address/page.tsx
  client/src/app/account/change-password/index.tsx
  client/src/app/account/change-password/page.tsx
  client/src/app/account/layout.tsx
  client/src/app/account/orders/index.tsx
  client/src/app/account/orders/page.tsx
  client/src/app/account/page.tsx
  client/src/app/account/profile/index.tsx
  client/src/app/account/profile/page.tsx
  client/src/components/Account/AccountLayout.jsx
  client/src/components/Account/Sidebar.jsx
  client/src/components/Account/SidebarContent.jsx
  client/src/components/Account/sidebar.tsx
  client/src/components/Account/sidebar_content.tsx
Labels: bug, feature

#28 fix bug #3
  client/src/app/cart/index.tsx
  client/src/app/cart/page.tsx
  client/src/components/Cart/index.tsx
Labels: bug

#27 fix bug profile page #2 v2
  client/src/components/Account/SidebarContent.tsx
  client/src/components/Account/contents/Addresss.jsx
  client/src/components/Account/contents/ChangePassword.jsx
  client/src/components/Account/contents/Orders.jsx
  client/src/components/Account/contents/Profile.jsx
  client/src/components/Account/index.css
  client/src/components/Account/sidebar.tsx
Labels: bug
